# Generated by Django 5.0.3 on 2024-04-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date published')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
            ],
        ),
    ]
