# Generated by Django 5.0.3 on 2024-04-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerino', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='My Gallery', max_length=60),
        ),
    ]
