# Generated by Django 5.0.3 on 2024-04-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerino', '0003_gallery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(default='gallerino_thumbnail_placeholder.png', upload_to='images/'),
        ),
    ]
