# Generated by Django 5.0.3 on 2024-04-28 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerino', '0004_alter_gallery_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallerino.gallery'),
        ),
    ]
