# Generated by Django 5.0.3 on 2024-04-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerino', '0009_gallery_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='testi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
