# Generated by Django 5.0.3 on 2024-04-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerino', '0012_gallery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='placeholder',
            field=models.BooleanField(default=True),
        ),
    ]
